version: '3.7'
services:
  # 1. Elasticsearch (存储日志)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # 2. Logstash (收集日志)
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.7
    container_name: logstash
    ports:
      - "5000:5000" # 对应 logback 里的端口
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  # 3. Kibana (可视化界面)
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  es_data: