input {
  tcp {
    mode => "server"
    host => "0.0.0.0"
    port => 5000
    codec => json_lines # 关键：解析 JSON 格式
  }
}

filter {
  # 这里可以做数据清洗，暂时留空
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "gateway-logs-%{+YYYY.MM.dd}" # 每天生成一个索引
  }
  stdout { codec => rubydebug } # 在 logstash 控制台也打印一份，方便调试
}