scrape_configs:
  - job_name: 'platform-gateway'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8082', 'host.docker.internal:8081' ]
